"use client";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <title> Create next app</title>
      <meta name="description" content="Generated by create next app" />
      </head>
      <body
        className={` antialiased`}>
        <ThemeProvider
          attribute="class"
          enableSystem
          defaultTheme="system"
          enableColorScheme
        >
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
